#Thu Sep 11 23:59:00 CEST 2025
micronaut:
  application:
    name: project-snake-backend
  http:
    services:
      user-service-client:
        url: https://auth.project-snake.win
      oauth-client:
        url: https://auth.project-snake.win
  jwt:
    jwk:
      url: https://auth.project-snake.win
      issuer: "https://auth.project-snake.win"

mongodb:
  servers:
    default:
      uri: "mongodb://${DB_USER}:${DB_USER_PWD}@localhost:27017/project-snake?retryWrites=false"

kinde:
  client-url: ${KINDE_HOST}
  client-id: ${KINDE_CLIENT_ID}
  client-secret: ${KINDE_CLIENT_SECRET}
  audience: ${TOKEN_AUDIENCE}